language: php

os:
  - linux

php:
  - 7.2
  - 7.3

matrix:
  include:
  - php: 7.2
    env: PHPSTAN=1

install:
    - composer self-update
    - composer install

script:
  - vendor/bin/codecept run
  - if [ "$PHPSTAN" = "1" ]; then composer run-script phpstan; fi
